import 'dart:typed_data';

import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:slot_game/src/game/audio_service.dart';
import 'package:slot_game/src/game/game_sound.dart';

void main() {
  // rootBundle needs the binding up before any asset can be read.
  TestWidgetsFlutterBinding.ensureInitialized();

  group('sound assets', () {
    test('every sound points at a real, playable WAV in the bundle', () async {
      // The clips are generated by tool/generate_sounds.py and declared in
      // pubspec.yaml. A renamed, missing or truncated file would otherwise only
      // show up as silence on a device.
      for (final GameSound sound in GameSound.values) {
        ByteData data;
        try {
          data = await rootBundle.load(sound.asset);
        } on Object catch (error) {
          fail('${sound.name}: ${sound.asset} is not in the bundle ($error)');
        }

        expect(
          data.lengthInBytes,
          greaterThan(2000),
          reason: '${sound.asset} is too small to hold a clip',
        );

        // RIFF header: "RIFF" .... "WAVE"
        String ascii(int start, int length) => String.fromCharCodes(
          Uint8List.view(data.buffer, data.offsetInBytes + start, length),
        );
        expect(ascii(0, 4), 'RIFF', reason: '${sound.asset} is not RIFF');
        expect(ascii(8, 4), 'WAVE', reason: '${sound.asset} is not WAVE');

        // fmt chunk: PCM, mono, 22050 Hz, as the generator writes.
        expect(ascii(12, 4), 'fmt ');
        expect(data.getUint16(20, Endian.little), 1, reason: 'not PCM');
        expect(data.getUint16(22, Endian.little), 1, reason: 'not mono');
        expect(data.getUint32(24, Endian.little), 22050, reason: 'sample rate');
        expect(data.getUint16(34, Endian.little), 16, reason: 'bit depth');
      }
    });

    test('every sound has its own clip', () {
      final Set<String> assets = GameSound.values
          .map((GameSound s) => s.asset)
          .toSet();
      expect(assets, hasLength(GameSound.values.length));
    });
  });

  group('silent service', () {
    test('records what it was asked to play', () {
      final SilentAudioService audio = SilentAudioService();
      addTearDown(audio.dispose);

      audio.play(GameSound.spinStart);
      audio.play(GameSound.reelStop);

      expect(audio.played, <GameSound>[
        GameSound.spinStart,
        GameSound.reelStop,
      ]);
    });

    test('plays nothing while muted', () async {
      final SilentAudioService audio = SilentAudioService(muted: true);
      addTearDown(audio.dispose);

      audio.play(GameSound.winBig);
      expect(audio.played, isEmpty);

      await audio.setMuted(false);
      audio.play(GameSound.winBig);
      expect(audio.played, <GameSound>[GameSound.winBig]);
    });

    test('tells listeners when muting changes, and only then', () async {
      final SilentAudioService audio = SilentAudioService();
      addTearDown(audio.dispose);
      int notifications = 0;
      audio.addListener(() => notifications++);

      await audio.setMuted(true);
      expect(notifications, 1);

      // Setting the same value again is not a change.
      await audio.setMuted(true);
      expect(notifications, 1);

      await audio.setMuted(false);
      expect(notifications, 2);
    });
  });
}
